# Question

Does the Pareto principle apply to this ecommerce?

# Preparing data

Import libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import functools as ft

Save data frames with correct data types

In [2]:
dir_pandas = '/datasets/drive/platzi_master/proyecto_1/{}'
items = pd.read_csv(dir_pandas.format('olist_order_items_dataset.csv')).convert_dtypes()
orders = pd.read_csv(dir_pandas.format('olist_orders_dataset.csv')).convert_dtypes()
products = pd.read_csv(dir_pandas.format('olist_products_dataset.csv')).convert_dtypes()

Merge data frames

In [3]:
dfs = [items, orders, products]
df = ft.reduce(lambda left, right: pd.merge(left, right), dfs)

Apply correct data type to date columns

In [4]:
df_time_columns = ['shipping_limit_date','order_purchase_timestamp','order_approved_at','order_delivered_carrier_date','order_delivered_customer_date','order_estimated_delivery_date']
df[df_time_columns] = df[df_time_columns].apply(pd.to_datetime)

Keep the original data frame and use a copy to the analysis

In [5]:
df_olist = df.copy()

# Analysis

Filter the data frame with succeed orders

In [6]:
total_orders = len(df_olist)
total_orders

112650

In [7]:
list(df_olist['order_status'].unique())

['delivered',
 'shipped',
 'canceled',
 'invoiced',
 'processing',
 'unavailable',
 'approved']

In [8]:
released_orders = df_olist.query('order_status != ["unavailable","canceled"]')
total_sales = len(released_orders)
total_sales

112101

In [9]:
released_share = total_sales / total_orders
released_share

0.9951264980026631

Describe data to find details

In [10]:
released_orders.describe(include='all', datetime_is_numeric=True)

order_id  order_item_id  \
count                             112101  112101.000000   
unique                             98199            NaN   
top     8272b63d03f5f79c56e9e4120aec44ef            NaN   
freq                                  21            NaN   
mean                                 NaN       1.197349   
min                                  NaN       1.000000   
25%                                  NaN       1.000000   
50%                                  NaN       1.000000   
75%                                  NaN       1.000000   
max                                  NaN      21.000000   
std                                  NaN       0.704307   

                              product_id                         seller_id  \
count                             112101                            112101   
unique                             32729                              3053   
top     aca2eb7d00ea1a7b8ebd4e68314663af  6560211a19b47992c3666cc44a7e94c0   
freq                                 527                              2025   
mean                                 NaN                               NaN   
min                                  NaN                               NaN   
25%                                  NaN                               NaN   
50%                                  NaN                               NaN   
75%                                  NaN                               NaN   
max                                  NaN                               NaN   
std                                  NaN                               NaN   

                  shipping_limit_date          price  freight_value  \
count                          112101  112101.000000  112101.000000   
unique                            NaN            NaN            NaN   
top                               NaN            NaN            NaN   
freq                              NaN            NaN            NaN   
mean    2018-01-07 19:28:06.622447616     120.377166      19.992028   
min               2016-09-19 23:11:33       0.850000       0.000000   
25%               2017-09-20 23:24:26      39.900000      13.080000   
50%               2018-01-26 13:59:24      74.900000      16.270000   
75%               2018-05-10 14:53:13     134.900000      21.150000   
max               2020-04-09 22:35:08    6735.000000     409.680000   
std                               NaN     182.637401      15.797782   

                             customer_id order_status  \
count                             112101       112101   
unique                             98199            5   
top     fc3d1daec319d62d49bfb5e1f83123e9    delivered   
freq                                  21       110197   
mean                                 NaN          NaN   
min                                  NaN          NaN   
25%                                  NaN          NaN   
50%                                  NaN          NaN   
75%                                  NaN          NaN   
max                                  NaN          NaN   
std                                  NaN          NaN   

             order_purchase_timestamp  ...  order_delivered_customer_date  \
count                          112101  ...                         110189   
unique                            NaN  ...                            NaN   
top                               NaN  ...                            NaN   
freq                              NaN  ...                            NaN   
mean    2018-01-01 04:20:37.930892544  ...  2018-01-14 13:59:34.689261568   
min               2016-09-04 21:15:19  ...            2016-10-11 13:46:32   
25%               2017-09-13 23:13:16  ...            2017-09-26 20:15:35   
50%               2018-01-19 22:20:50  ...            2018-02-02 21:05:09   
75%               2018-05-04 17:51:51  ...            2018-05-15 20:14:33   
max               2018-09-03 09:06:57  ...            2018-10-17 13:22:46   
s

In [11]:
released_orders.nunique()

order_id                         98199
order_item_id                       21
product_id                       32729
seller_id                         3053
shipping_limit_date              92883
price                             5934
freight_value                     6985
customer_id                      98199
order_status                         5
order_purchase_timestamp         97647
order_approved_at                89757
order_delivered_carrier_date     80950
order_delivered_customer_date    95658
order_estimated_delivery_date      447
product_category_name               73
product_name_lenght                 66
product_description_lenght        2957
product_photos_qty                  19
product_weight_g                  2193
product_length_cm                   99
product_height_cm                  102
product_width_cm                    95
dtype: int64

In [25]:
released_orders.head(1)

order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1   

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   

  shipping_limit_date  price  freight_value                       customer_id  \
0 2017-09-19 09:45:35   58.9          13.29  3ce436f183e68e07877b285a838db11a   

  order_status order_purchase_timestamp  ... order_delivered_customer_date  \
0    delivered      2017-09-13 08:59:02  ...           2017-09-20 23:43:48   

  order_estimated_delivery_date product_category_name product_name_lenght  \
0                    2017-09-29            cool_stuff                  58   

  product_description_lenght  product_photos_qty  product_weight_g  \
0                        598                   4               650   

   product_length_cm  product_height_cm  product_width_cm  
0                 28                  9                14  

[1 rows x 22 columns]

In [24]:
for key_group, group in released_orders.head(1).groupby('seller_id'):
    print('key: {} \n group: {}'.format(key_group, group))

key: 48436dade18ac8b2bce089ec2a041202 
 group:                            order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1   

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202   

  shipping_limit_date  price  freight_value                       customer_id  \
0 2017-09-19 09:45:35   58.9          13.29  3ce436f183e68e07877b285a838db11a   

  order_status order_purchase_timestamp  ... order_delivered_customer_date  \
0    delivered      2017-09-13 08:59:02  ...           2017-09-20 23:43:48   

  order_estimated_delivery_date product_category_name product_name_lenght  \
0                    2017-09-29            cool_stuff                  58   

  product_description_lenght  product_photos_qty  product_weight_g  \
0                        598                   4               650   

   product_length_cm  product_height_cm  product_width_cm  
0                 28 

Group information by top sellers

In [12]:
top_sellers = (
    released_orders.groupby("seller_id")
    .aggregate(
        {
            "order_item_id": "count",
            "product_category_name": pd.Series.mode,
            "price": "mean",
        }
    )
    .sort_values(by="order_item_id", ascending=False)
)
top_sellers


order_item_id        product_category_name  \
seller_id                                                                      
6560211a19b47992c3666cc44a7e94c0           2025           relogios_presentes   
4a3ca9315b744ce9f8e9374361493884           1985              cama_mesa_banho   
1f50f920176fa81dab994f9023523100           1930           ferramentas_jardim   
cc419e0650a3c5ba77189a1882b7556a           1766                 beleza_saude   
da8622b14eb17ae2831f4ac5b9dab84a           1551              cama_mesa_banho   
...                                         ...                          ...   
6c6cc59a5c00cacc5054ca06d65cc282              1                     pet_shop   
dde698c6d0bd24834c586e5111c2bba7              1  fashion_bolsas_e_acessorios   
dda37071807e404c5bb2a1590c66326f              1             malas_acessorios   
dd9661d3cda1e6feb237f0c4d8b26f2e              1        utilidades_domesticas   
da4d149c0ddbac90557103ac0a0ec356              1              casa_construcao   

                                       price  
seller_id                                     
6560211a19b47992c3666cc44a7e94c0   60.630533  
4a3ca9315b744ce9f8e9374361493884   100.91996  
1f50f920176fa81dab994f9023523100   55.383062  
cc419e0650a3c5ba77189a1882b7556a   58.683188  
da8622b14eb17ae2831f4ac5b9dab84a  103.311779  
...                                      ...  
6c6cc59a5c00cacc5054ca06d65cc282      1107.0  
dde698c6d0bd24834c586e5111c2bba7       155.9  
dda37071807e404c5bb2a1590c66326f      199.99  
dd9661d3cda1e6feb237f0c4d8b26f2e       174.0  
da4d149c0ddbac90557103ac0a0ec356       730.0  

[3053 rows x 3 columns]

Find the most sold category

In [13]:
top_category = top_sellers['product_category_name'].value_counts().idxmax()
top_category

'beleza_saude'

In [14]:
total_sellers = len(top_sellers)
total_sellers

3053

In [15]:
pareto_sales = total_sales * 0.8
pareto_sales

89680.8

Accumulate sales by seller to find de the Pareto sales number

In [16]:
top_sellers['cum_sales'] = top_sellers['order_item_id'].cumsum()
top_sellers

order_item_id        product_category_name  \
seller_id                                                                      
6560211a19b47992c3666cc44a7e94c0           2025           relogios_presentes   
4a3ca9315b744ce9f8e9374361493884           1985              cama_mesa_banho   
1f50f920176fa81dab994f9023523100           1930           ferramentas_jardim   
cc419e0650a3c5ba77189a1882b7556a           1766                 beleza_saude   
da8622b14eb17ae2831f4ac5b9dab84a           1551              cama_mesa_banho   
...                                         ...                          ...   
6c6cc59a5c00cacc5054ca06d65cc282              1                     pet_shop   
dde698c6d0bd24834c586e5111c2bba7              1  fashion_bolsas_e_acessorios   
dda37071807e404c5bb2a1590c66326f              1             malas_acessorios   
dd9661d3cda1e6feb237f0c4d8b26f2e              1        utilidades_domesticas   
da4d149c0ddbac90557103ac0a0ec356              1              casa_construcao   

                                       price  cum_sales  
seller_id                                                
6560211a19b47992c3666cc44a7e94c0   60.630533       2025  
4a3ca9315b744ce9f8e9374361493884   100.91996       4010  
1f50f920176fa81dab994f9023523100   55.383062       5940  
cc419e0650a3c5ba77189a1882b7556a   58.683188       7706  
da8622b14eb17ae2831f4ac5b9dab84a  103.311779       9257  
...                                      ...        ...  
6c6cc59a5c00cacc5054ca06d65cc282      1107.0     112097  
dde698c6d0bd24834c586e5111c2bba7       155.9     112098  
dda37071807e404c5bb2a1590c66326f      199.99     112099  
dd9661d3cda1e6feb237f0c4d8b26f2e       174.0     112100  
da4d149c0ddbac90557103ac0a0ec356       730.0     112101  

[3053 rows x 4 columns]

Filter the Pareto sellers

In [17]:
pareto_sellers = len(top_sellers[top_sellers['cum_sales'] <= pareto_sales])
pareto_sellers

535

In [18]:
pareto = pareto_sellers / total_sellers
pareto

0.1752374713396659

# Conclusions

## Insights

* There are 112650 orders and 112101 were released orders, that is 99.5%.

* The most sold category is Beleza Saude (Health Beauty).

* The released orders were sold by 3053 sellers.

* The 80% of the total released orders is 89680 orders, and were sold by 535 sellers, that is 17.5%, confirming the Pareto principle.

## Conclusion

The Pareto principle applies for Olist ecommerce. The ecommerce could focus resources in these 535 sellers to optimize resources to grow in income sales.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=121826e1-6393-4f2b-82a6-a1186eee7df2' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>